### PR TITLE
Fix : Browserify compatibility of the library.

### PR DESCRIPTION
**Pull request by bobylito**
- Remove setTimeout, not supported by browserify/http and not used in our
code.
 - Make the chunks compatible with the web
 - Bump version 1.7.6

cc/ @speedblue @speedblue @vvo

### CODE REVIEW

**Comment by vvo** [comment]
LGTM

**Comment by vvo** [comment]
Oh, you can also remove buffers dependency.

**Comment by vvo** [comment]
Buffer.concat breaks compat with node < 8, so change in package.json that we support "only" node >= 8.

If a client uses nodejs 0.6 then he has a lot more problems maybe.

**Comment by vvo** [comment]
Ref: https://github.com/coolaj86/node-bufferjs#bufferconcatlist-totallength

**Comment by redox** [comment]
Could you also patch the travis.yml to test multiple versions of node (and iojs?)

**Comment by bobylito** [comment]
btw, could you comment in the files changed tab instead of a specific commit. This way github tracks if there changes in the source around the comment and discard it. Also it is more practical for commenting back. :)

**Comment by bobylito** [comment]
Ok we have CI fails here. Seems like the key is not yet deleted when we ask for the number of keys. It seems like the wait time of 5 is not enough. Should we go for 10?

**Comment by redox** [comment]
Yes, depending on the load it can happen.

**Comment by vvo** [comment]
we will have to change testing strategy.

**Comment by bobylito** [comment]
So the idea is that it could happen for any of the API calls? Or is it specific to this call (delete a user key)

**Comment by redox** [comment]
It's specific to API keys, that are not generating taskIDs. Ideally, those indexing job should generate taskIDs so we can waitTask.

**Comment by vvo** [comment]
> btw, could you comment in the files changed tab instead of a specific commit? This way github tracks if there changes in the source around the comment and discard it. Also it is more practical for commenting back. :)

Yes I think I did a comment in the crappy android app

**Comment by bobylito** [comment]
We'll fix the test with a more reliable solution when we merge both JS clients. In the meantime, let's merge!

**Comment by vvo** [comment]
Yes, I saw the tests passes on @bobylito laptop, the only problem is that tests are using too much network and so fails sometimes.

**Pull request merged**
